ci:
    autofix_prs: false
    skip: [legacy_precommit]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-ast
    -   id: check-yaml
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: pretty-format-json
        args: [--autofix]
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
    -  id: black
-   repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        # TODO: I think this is an old arg that can be deleted.
        args: ["--extend-exclude=*_pb2.py"]
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    - id: isort
      name: isort (python)
      args: ["--profile", "black"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
    -   id: mypy
        args: ["--strict"]
        additional_dependencies: [mutagen==1.47.0]
-   repo: local
    hooks:
    # TODO: Everything should be migrated out of this legacy precommit step.
    -   id: legacy_precommit
        name: legacy_precommit
        entry: python pre-commit.py
        language: system
        always_run: true
        pass_filenames: false
